name: Markdown Lint & Spell Check

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install linters
      run: npm install -g markdownlint-cli cspell

    - name: Run markdownlint
      run: markdownlint '**/*.md'

    - name: Run cspell
      run: cspell '**/*.md'
