name: Markdown Lint and Spell Check

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install -g markdownlint-cli markdown-spellcheck
      - name: Run Markdown linting
        run: markdownlint '**/*.md'
      - name: Run spell check
        run: markdown-spellcheck '**/*.md'
